# Importando a biblioteca Pandas
Sabemos que para importar um biblioteca usamos o comando **`import`** e caso se queira dar um nome diferente usamos a **`as`** veja no código baixo:

In [1]:
import pandas as pd #importando a biblioteca pandas
#importando outras bibliotecas que serão usadas.
import requests
import json
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect
import lxml

## Importando os dados
Para realizar a importação de dados temos algumas formas que serão listadas respectivamente:
<ul>
    <li>Importando de um arquivo .xlsx</li>
    <li>Importando de um arquivo .csv</li>
    <li>Importando de um arquivo .csv em um link</li>
</ul>

In [2]:
#importando de um arquivo .xlsx
xlsx = pd.ExcelFile('dados_vendas.xlsx')#aqui coloca-se o nome do arquivo
#Lembre-se de colocar o caminha completo se não estiver no mesmo diretorio do código
df = pd.read_excel(xlsx, 'Pasta1') #Neste exemplo nossos dados estão na 'Pasta1'
#Atente-se para o nome da planilha onde estão os dados, pois um arquivo pode conter muitas planilhas

In [3]:
#Para ler arquivos CSV codificados em ISO
df2 = pd.read_csv('Credit.csv')
#Lembre-se de colocar o caminha completo se não estiver no mesmo diretorio do código

### Parametros da função para arquivos .csv
<table style="width:100%">
    <tr>
        <th style="width:10%">Parâmetro</th>
        <th>Para que serve?</th>
        <th>Exemplo de Código</th>
    </tr>
    <tr>
        <td style="width:10%">sep ou delimiter</td>
        <td>Define o caractere que separa as colunas. O padrão é a vírgula (,). Muito útil usar ; para arquivos brasileiros.</td>
        <td>pd.read_csv('dados.csv', sep=';')</td>
    </tr>
    <tr>
        <td style="width:10%">encoding</td>
        <Td>Define a codificação de caracteres. Use latin-1 ou utf-8 se o seu arquivo tiver acentos ou caracteres especiais quebrados.</Td>
        <td>pd.read_csv('dados.csv', encoding='latin-1')</td>
    </tr>
    <tr>
        <td style="width:10%">usecols</td>
        <td>Carrega apenas as colunas que você especificar, economizando memória.</td>
        <td>pd.read_csv('dados.csv', usecols=['Nome', 'Idade'])</td>
    </tr>
	<tr>
        <td>nrows</td>
        <td>Limita a quantidade de linhas lidas (ótimo para testar arquivos gigantes).</td>
        <td>pd.read_csv('dados.csv', nrows=100)</td>
    </tr>
    <tr>
        <td style="width:10%">parse_dates</td>
        <td>Converte colunas de texto com datas diretamente no formato de data (datetime) do Python.</td>
        <td>pd.read_csv('dados.csv', parse_dates=['Data_Venda'])</td>
    </tr>
    <tr>
        <td style="width:10%">decimal</td>
        <td>Altera o separador decimal. No Brasil, usamos a vírgula (,) para decimais em vez de ponto (.).</td>
        <td>pd.read_csv('dados.csv', decimal=',')</td>
    </tr>
</table>

In [4]:
#Caso queira pegar um arquivo que esteja em um link basta então somente colocar a url no lugar do arquivo
url = 'https://raw.githubusercontent.com/alura-cursos/pandas/main/superstore_data.csv' #salvando em uma variável para organizar melhor.
dados_superstore = pd.read_csv(url)

Agora vamos mostrar apenas as 5 primeiras linhas do nosso datafreme com o comando `.head()`

In [5]:
df.head() #Observe que quando pegamos um dataframe(df) com menos que 5 linhas ele mostra todas as linhas que tem no df

,ID_Pedido,Data,Produto,Categoria,Quantidade,Valor_Unitario,Regiao
0,1,2026-01-10,Notebook,Eletrônicos,1,3500,Sudeste
1,2,2026-01-11,Smartphone,Eletrônicos,2,1200,Nordeste
2,3,2026-01-12,Cadeira Gamer,Móveis,2,850,Sul
3,4,2026-01-13,"Monitor 24""",Eletrônicos,2,900,Sudeste
4,5,2026-01-14,Mesa Escritório,Móveis,2,450,Centro-Oeste

In [6]:
df2.head() #Quando o df é maior ele mostra apenas as 5 primeiras linhas com todas as colunas.

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [7]:
dados_superstore.head() # Veja outro exemplo

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [8]:
#É possível salvar apenas as 5 primeiras linhas ou quantas linhas desejarmos
dados_primeiras_linhas = pd.read_csv(url,nrows=5)

In [9]:
dados_primeiras_linhas #Exibindo df completo

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [10]:
dados_selecao = pd.read_csv(url, usecols=['Id', 'Year_Birth', 'Income'])# É possível ainda selecionar as colunas desejadas

In [11]:
dados_selecao #Exibindo df completo

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [12]:
dados_selecao = pd.read_csv(url, usecols=[0,1,4]) #É possivel selecionar as colunas tanto pelo nome quando pelo index

In [13]:
dados_selecao #Exibindo df completo

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [ ]:
#Caso queira pegar um arquivo do tipo excel que esteja em um link basta fazer o mesmo que no .csv colocar a url no lugar do arquivo 
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'
dados_co2 = pd.read_excel(url)

In [ ]:
dados_co2 #Exibindo df completo

In [ ]:
pd.ExcelFile(url).sheet_names #comando para verificar quais planilhas o arquivo excel possui

In [ ]:
chave = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'
url=f'https://docs.google.com/spreadsheets/d/{chave}/gviz/tq?tqx=out:csv&sheet'
co2_per_capita = pd.read_csv(url)

In [ ]:
co2_per_capita.to_csv('co2_per_capita.csv', index = False, sep = ';')
co2_per_capita

#### Pegando informações de um JSON para colocar em um DataFrame

In [14]:
dados_frutas = requests.get('https://fruityvice.com/api/fruit/all') #Pegando uma url através do get request
dados_frutas #Exibindo a resposta

In [15]:
resultado = json.loads(dados_frutas.text) #pegando a resposta do get para um json
resultado #exibindo o JSON

[{'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 81,
   'fat': 0.0,
   'sugar': 18.0,
   'carbohydrates': 18.0,
   'protein': 0.0}},
 {'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.8}},
 {'name': 'Banana',
  'id': 1,
  'family': 'Musaceae',
  'order': 'Zingiberales',
  'genus': 'Musa',
  'nutritions': {'calories': 96,
   'fat': 0.2,
   'sugar': 17.2,
   'carbohydrates': 22.0,
   'protein': 1.0}},
 {'name': 'Tomato',
  'id': 5,
  'family': 'Solanaceae',
  'order': 'Solanales',
  'genus': 'Solanum',
  'nutritions': {'calories': 74,
   'fat': 0.2,
   'sugar': 2.6,
   'carbohydrates': 3.9,
   'protein': 0.9}},
 {'name': 'Pear',
  'id': 4,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Pyrus',
  'nutritions': {'calories': 57,
   'fat': 0.1,
   'sugar': 10.0,
   'carbohydrates': 15.0,
   'protein': 0.4}},
 {'name': 'Durian',
  'id': 60,
  'family': 'Malvaceae',
  'order': 'Malvales',
  'genus': 'Durio',
  'nutritions': {'calories': 147,
   'fat': 5.3,
   'sugar': 6.75,
   'carbohydrates': 27.1,
   'protein': 1.5}},
 {'name': 'Blackberry',
  'id': 64,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 40,
   'fat': 0.4,
   'sugar': 4.5,
   'carbohydrates': 9.0,
   'protein': 1.3}},
 {'name': 'Lingonberry',
  'id': 65,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 50,
   'fat': 0.34,
   'sugar': 5.74,
   'carbohydrates': 11.3,
   'protein': 0.75}},
 {'name': 'Kiwi',
  'id': 66,
  'family': 'Actinidiaceae',
  'order': 'Struthioniformes',
  'genus': 'Apteryx',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 9.0,
   'carbohydrates': 15.0,
   'protein': 1.1}},
 {'name': 'Lychee',
  'id': 67,
  'family': 'Sapindaceae',
  'order': 'Sapindales',
  'genus': 'Litchi',
  'nutritions': {'calories': 66,
   'fat': 0.44,
   'sugar': 15.0,
   'carbohydrates': 17.0,
   'protein': 0.8}},
 {'name': 'Pineapple',
  'id': 10,
  'family': 'Bromeliaceae',
  'order': 'Poales',
  'genus': 'Ananas',
  'nutritions': {'calories': 50,
   'fat': 0.12,
   'sugar': 9.85,
   'carbohydrates': 13.12,
   'protein': 0.54}},
 {'name': 'Fig',
  'id': 68,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Ficus',
  'nutritions': {'calories': 74,
   'fat': 0.3,
   'sugar': 16.0,
   'carbohydrates': 19.0,
   'protein': 0.8}},
 {'name': 'Gooseberry',
  'id': 69,
  'family': 'Grossulariaceae',
  'order': 'Saxifragales',
  'genus': 'Ribes',
  'nutritions': {'calories': 44,
   'fat': 0.6,
   'sugar': 0.0,
   'carbohydrates': 10.0,
   'protein': 0.9}},
 {'name': 'Passionfruit',
  'id': 70,
  'family': 'Passifloraceae',
  'order': 'Malpighiales',
  'genus': 'Passiflora',
  'nutritions': {'calories': 97,
   'fat': 0.7,
   'sugar': 11.2,
   'carbohydrates': 22.4,
   'protein': 2.2}},
 {'name': 'Plum',
  'id': 71,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 46,
   'fat': 0.28,
   'sugar': 9.92,
   'carbohydrates': 11.4,
   'protein': 0.7}},
 {'name': 'Orange',
  'id': 2,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 43,
   'fat': 0.2,
   'sugar': 8.2,
   'carbohydrates': 8.3,
   'protein': 1.0}},
 {'name': 'GreenApple',
  'id': 72,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 21,
   'fat': 0.1,
   'sugar': 6.4,
   'carbohydrates': 3.1,
   'protein': 0.4}},
 {'name': 'Raspberry',
  'id': 23,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 53,
   'fat': 0.7,
   'sugar': 4.4,
   'carbohydrates': 12.0,
   'protein': 1.2}},
 {'name': 'Watermelon',
  'id': 25,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Citrullus',
  'nutritions': {'calories': 30,
   'fat': 0.2,
   'sugar': 6.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Lemon',
  'id': 26,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 29,
   'fat': 0.3,
   'sugar': 2.5,
   'carbohydrates': 9.0,
   'protein': 1.1}},
 {'name': 'Mango',
  'id': 27,
  'family': 'Anacardiaceae',
  'order': 'Sapindales',
  'genus': 'Mangifera',
  'nutritions': {'calories': 60,
   'fat': 0.38,
   'sugar': 13.7,
   'carbohydrates': 15.0,
   'protein': 0.82}},
 {'name': 'Blueberry',
  'id': 33,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.0}},
 {'name': 'Apple',
  'id': 6,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 52,
   'fat': 0.4,
   'sugar': 10.3,
   'carbohydrates': 11.4,
   'protein': 0.3}},
 {'name': 'Guava',
  'id': 37,
  'family': 'Myrtaceae',
  'order': 'Myrtales',
  'genus': 'Psidium',
  'nutritions': {'calories': 68,
   'fat': 1.0,
   'sugar': 9.0,
   'carbohydrates': 14.0,
   'protein': 2.6}},
 {'name': 'Apricot',
  'id': 35,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 15,
   'fat': 0.1,
   'sugar': 3.2,
   'carbohydrates': 3.9,
   'protein': 0.5}},
 {'name': 'Melon',
  'id': 41,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitaceae',
  'genus': 'Cucumis',
  'nutritions': {'calories': 34,
   'fat': 0.0,
   'sugar': 8.0,
   'carbohydrates': 8.0,
   'protein': 0.0}},
 {'name': 'Tangerine',
  'id': 77,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 45,
   'fat': 0.4,
   'sugar': 9.1,
   'carbohydrates': 8.3,
   'protein': 0.0}},
 {'name': 'Pitahaya',
  'id': 78,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Cactaceae',
  'nutritions': {'calories': 36,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 7.0,
   'protein': 1.0}},
 {'name': 'Lime',
  'id': 44,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 25,
   'fat': 0.1,
   'sugar': 1.7,
   'carbohydrates': 8.4,
   'protein': 0.3}},
 {'name': 'Pomegranate',
  'id': 79,
  'family': 'Lythraceae',
  'order': 'Myrtales',
  'genus': 'Punica',
  'nutritions': {'calories': 83,
   'fat': 1.2,
   'sugar': 13.7,
   'carbohydrates': 18.7,
   'protein': 1.7}},
 {'name': 'Dragonfruit',
  'id': 80,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Selenicereus',
  'nutritions': {'calories': 60,
   'fat': 1.5,
   'sugar': 8.0,
   'carbohydrates': 9.0,
   'protein': 9.0}},
 {'name': 'Grape',
  'id': 81,
  'family': 'Vitaceae',
  'order': 'Vitales',
  'genus': 'Vitis',
  'nutritions': {'calories': 69,
   'fat': 0.16,
   'sugar': 16.0,
   'carbohydrates': 18.1,
   'protein': 0.72}},
 {'name': 'Morus',
  'id': 82,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Morus',
  'nutritions': {'calories': 43,
   'fat': 0.39,
   'sugar': 8.1,
   'carbohydrates': 9.8,
   'protein': 1.44}},
 {'name': 'Feijoa',
  'id': 76,
  'family': 'Myrtaceae',
  'order': 'Myrtoideae',
  'genus': 'Sellowiana',
  'nutritions': {'calories': 44,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Avocado',
  'id': 84,
  'family': 'Lauraceae',
  'order': 'Laurales',
  'genus': 'Persea',
  'nutritions': {'calories': 160,
   'fat': 14.66,
   'sugar': 0.66,
   'carbohydrates': 8.53,
   'protein': 2.0}},
 {'name': 'Kiwifruit',
  'id': 85,
  'family': 'Actinidiaceae',
  'order': 'Ericales',
  'genus': 'Actinidia',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 8.9,
   'carbohydrates': 14.6,
   'protein': 1.14}},
 {'name': 'Cranberry',
  'id': 87,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 46,
   'fat': 0.1,
   'sugar': 4.0,
   'carbohydrates': 12.2,
   'protein': 0.4}},
 {'name': 'Cherry',
  'id': 9,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 50,
   'fat': 0.3,
   'sugar': 8.0,
   'carbohydrates': 12.0,
   'protein': 1.0}},
 {'name': 'Peach',
  'id': 86,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 39,
   'fat': 0.25,
   'sugar': 8.4,
   'carbohydrates': 9.5,
   'protein': 0.9}},
 {'name': 'Jackfruit',
  'id': 94,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Artocarpus',
  'nutritions': {'calories': 95,
   'fat': 0.0,
   'sugar': 19.1,
   'carbohydrates': 23.2,
   'protein': 1.72}},
 {'name': 'Horned Melon',
  'id': 95,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucumis',
  'nutritions': {'calories': 44,
   'fat': 1.26,
   'sugar': 0.5,
   'carbohydrates': 7.56,
   'protein': 1.78}},
 {'name': 'Hazelnut',
  'id': 96,
  'family': 'Betulaceae',
  'order': 'Fagales',
  'genus': 'Corylus',
  'nutritions': {'calories': 628,
   'fat': 61.0,
   'sugar': 4.3,
   'carbohydrates': 17.0,
   'protein': 15.0}},
 {'name': 'Pomelo',
  'id': 98,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 37,
   'fat': 0.0,
   'sugar': 8.5,
   'carbohydrates': 9.67,
   'protein': 0.82}},
 {'name': 'Mangosteen',
  'id': 99,
  'family': 'Clusiaceae',
  'order': 'Malpighiales',
  'genus': 'Garcinia',
  'nutritions': {'calories': 73,
   'fat': 0.58,
   'sugar': 16.11,
   'carbohydrates': 17.91,
   'protein': 0.41}},
 {'name': 'Pumpkin',
  'id': 100,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucurbita',
  'nutritions': {'calories': 25,
   'fat': 0.3,
   'sugar': 3.3,
   'carbohydrates': 4.6,
   'protein': 1.1}},
 {'name': 'Japanese Persimmon',
  'id': 101,
  'family': ' Ebenaceae',
  'order': ' Ericales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 70,
   'fat': 0.2,
   'sugar': 13.0,
   'carbohydrates': 19.0,
   'protein': 0.6}},
 {'name': 'Papaya',
  'id': 42,
  'family': 'Caricaceae',
  'order': 'Brassicales',
  'genus': 'Carica',
  'nutritions': {'calories': 39,
   'fat': 0.3,
   'sugar': 4.4,
   'carbohydrates': 5.8,
   'protein': 0.5}},
 {'name': 'Annona',
  'id': 103,
  'family': 'Annonaceae',
  'order': 'Rosales',
  'genus': 'Annonas',
  'nutritions': {'calories': 92,
   'fat': 0.29,
   'sugar': 3.4,
   'carbohydrates': 19.1,
   'protein': 1.5}},
 {'name': 'Ceylon Gooseberry',
  'id': 104,
  'family': 'Salicaceae',
  'order': 'Malpighiales',
  'genus': 'Dovyalis',
  'nutritions': {'calories': 47,
   'fat': 0.3,
   'sugar': 8.1,
   'carbohydrates': 9.6,
   'protein': 1.2}}]

In [16]:
df_normalizado = pd.json_normalize(resultado) #Pegando um JSON para um df usando pandas
df_normalizado #Exibindo dataframe completo.

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

### Usando Banco de dados com Pandas
Executaremos agora um comando para criar uma conexão com um banco de dados SQLite temporário que roda 100% dentro da memória RAM do seu computador.
<ul>
    <li>Primeiro temos `create_engine(...)` uma função da biblioteca SQLAlchemy (a ferramenta de conexão padrão usada pelo Pandas) que funciona como a "ponte" ou o "tradutor" entre o seu código Python e o banco de dados. É ela quem gerencia o envio dos dados do seu DataFrame para as tabelas do banco.
    </li>
    <li>
        Depois `'sqlite://'` temos a string que indica o driver do banco de dados que será usado. Neste caso o SQLite é um banco de dados leve, que não precisa de servidor, usuário ou senha instalados na máquina — ele já vem nativo no Python.
    </li>
    <li>Por último temos `'/:memory:'` (O segredo do comando) que em vez de salvar as tabelas em um arquivo físico no seu disco rígido (como banco.db), diz ao sistema para criar um banco de dados "fantasma" dentro da memória RAM.
    </li>
</ul>

In [127]:
engine = create_engine('sqlite:///:memory:')# Criando uma conexão conexão com um banco SQLite (ou MySQL, PostgreSQL, etc.)

In [128]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
dados = pd.read_csv(url)
dados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

### Salvando o conteúdo de um DataFrame do Pandas diretamente em uma tabela
**1.** `dados.to_sql(...)`: É o método do Pandas que converte a estrutura do DataFrame em comandos SQL de inserção (INSERT INTO) e os executa no banco de dados.

**2.** `'clientes'`: É o nome da tabela que será criada ou modificada dentro do seu banco de dados. Se a tabela já existir, o Pandas tentará inserir os dados nela.

**3.** `engine`: É o motor de conexão com o banco de dados. Ele armazena as credenciais e o endereço (como usuário, senha, host, porta e nome do banco). Geralmente ele é criado antes usando a biblioteca SQLAlchemy:
python

**4.** `index=False`: Por padrão, o Pandas trata o índice do DataFrame (aqueles números 0, 1, 2... ou nomes na lateral esquerda) como se fossem uma coluna comum e tenta salvá-los no banco de dados.
• `index=False`: Diz ao Pandas para ignorar o índice e salvar apenas as colunas de dados reais (como Nome, Idade, Email, etc.).
• Se você esquecer de colocar isso: O banco de dados criará uma coluna extra chamada index ou level_0, o que costuma desorganizar tabelas de produção.

**Um parâmetro extra que você provavelmente vai precisar: if_exists**

Por padrão, se a tabela `'clientes'` já existir no seu banco de dados, esse código vai dar um erro. Para evitar isso, você deve adicionar o parâmetro if_exists:
* `if_exists='append'`: Adiciona os novos dados no final da tabela que já existe.
* `if_exists='replace'`: Apaga a tabela antiga inteira e cria uma nova do zero com os novos dados.

In [129]:
dados.to_sql('clientes', engine, index=False)

438463

O comando `inspector = inspect(engine)` serve para criar um objeto capaz de **"olhar por dentro" do seu banco de dados** e ler a estrutura dele (os metadados), sem que você precise rodar comandos SQL manuais para isso.

In [130]:
inspector = inspect(engine)

In [131]:
#Mostrando todas as tabelas do banco de dados
print(inspector.get_table_names())

['clientes']

Agora vamos fazer uma requisições para esse banco de dados

In [132]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renda="Empregado"'
empregados = pd.read_sql(query, engine)
empregados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [133]:
#Adicionando outra tabela ao banco de dados
empregados.to_sql('empregados', con=engine, index=False)

226059

In [134]:
#Mostrando todas as tabelas do banco de dados
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empregados']

O comando `pd.read_sql_table('clientes', engine)` serve para trazer uma tabela inteira do banco de dados diretamente para um DataFrame do Pandas, sem que você precise escrever nenhuma linha de código SQL (como `SELECT * FROM...`).

In [135]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [136]:
from sqlalchemy import text
query = "DELETE FROM clientes WHERE ID_Cliente=5008804;"
with engine.connect() as conn:
    conn.execute(text(query))

In [39]:
query = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'
with engine.connect() as conn:
    conn.execute(text(query))

In [40]:
query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, '\
        'Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, ' \
        'Anos_empregado, Rendimento_anual, Tem_carro, Moradia) ' \
        'VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", ' \
        '2, 290000, 0, "Casa/apartamento próprio")'
with engine.connect() as conn:
    conn.execute(text(query))

### Operando com DataFrames

In [42]:
#Removendo linhas pelo index
df.drop([0, 1])# Para salvar temos que atribuir isso a uma variável

,ID_Pedido,Data,Produto,Categoria,Quantidade,Valor_Unitario,Regiao
2,3,2026-01-12,Cadeira Gamer,Móveis,2,850,Sul
3,4,2026-01-13,"Monitor 24""",Eletrônicos,2,900,Sudeste
4,5,2026-01-14,Mesa Escritório,Móveis,2,450,Centro-Oeste
5,6,2026-01-15,Teclado Mecânico,Acessórios,1,250,Norte

In [43]:
#Removendo colunas utilizando o argumento axis=1
df.drop('Quantidade', axis=1) # Para salvar temos que atribuir isso a uma variável

,ID_Pedido,Data,Produto,Categoria,Valor_Unitario,Regiao
0,1,2026-01-10,Notebook,Eletrônicos,3500,Sudeste
1,2,2026-01-11,Smartphone,Eletrônicos,1200,Nordeste
2,3,2026-01-12,Cadeira Gamer,Móveis,850,Sul
3,4,2026-01-13,"Monitor 24""",Eletrônicos,900,Sudeste
4,5,2026-01-14,Mesa Escritório,Móveis,450,Centro-Oeste
5,6,2026-01-15,Teclado Mecânico,Acessórios,250,Norte

In [44]:
df  #Como não atribuimos as operações anteriores a variável df ela continua com o df original

,ID_Pedido,Data,Produto,Categoria,Quantidade,Valor_Unitario,Regiao
0,1,2026-01-10,Notebook,Eletrônicos,1,3500,Sudeste
1,2,2026-01-11,Smartphone,Eletrônicos,2,1200,Nordeste
2,3,2026-01-12,Cadeira Gamer,Móveis,2,850,Sul
3,4,2026-01-13,"Monitor 24""",Eletrônicos,2,900,Sudeste
4,5,2026-01-14,Mesa Escritório,Móveis,2,450,Centro-Oeste
5,6,2026-01-15,Teclado Mecânico,Acessórios,1,250,Norte

In [45]:
#Quantidade de linhas e colunas do DataFrame
df.shape

(6, 7)

In [46]:
#Descrição do Index
df.index

RangeIndex(start=0, stop=6, step=1)

In [47]:
#Colunas presentes no DataFrame
df.columns

Index(['ID_Pedido', 'Data', 'Produto', 'Categoria', 'Quantidade',
       'Valor_Unitario', 'Regiao'],
      dtype='str')

In [48]:
#Contagem de dados não-nulos
df.count()

ID_Pedido         6
Data              6
Produto           6
Categoria         6
Quantidade        6
Valor_Unitario    6
Regiao            6
dtype: int64

In [49]:
#Criando uma nova coluna em um DataFrame:
df['Nova Coluna'] = 0

In [139]:
#Renomeando colunas de um DataFrame:
#Se seu DataFrame possui 3 colunas, passe 3 novos valores em uma lista
df.columns = ['ID_Pedido', 'Data', 'Produto', 'Categoria', 'Quantidade','Valor_Unitario', 'Regiao', "Total"]

In [78]:
#Soma dos valores de uma coluna de um DataFrame
df["Valor_Unitario"].sum()

np.int64(7150)

In [80]:
#Soma dos valores das colunas que contém números em um DataFrame
df.select_dtypes(include='number').sum()

ID_Pedido           21
Quantidade          10
Valor_Unitario    7150
Total                0
dtype: int64

In [82]:
#Menor valor de um DataFrame
df.select_dtypes(include='number').min()

ID_Pedido           1
Quantidade          1
Valor_Unitario    250
Total               0
dtype: int64

In [83]:
#Maior valor
df.select_dtypes(include='number').max()

ID_Pedido            6
Quantidade           2
Valor_Unitario    3500
Total                0
dtype: int64

In [88]:
#Index do menor valor
df.select_dtypes(include='number').idxmin()

ID_Pedido         0
Quantidade        0
Valor_Unitario    5
Total             0
dtype: int64

In [89]:
#Index do maior valor
df.select_dtypes(include='number').idxmax()

ID_Pedido         5
Quantidade        1
Valor_Unitario    0
Total             0
dtype: int64

In [90]:
#Resumo estatístico do DataFrame, com quartis, mediana, etc.
df.describe()

       ID_Pedido                 Data  Quantidade  Valor_Unitario  Total
count   6.000000                    6    6.000000        6.000000    6.0
mean    3.500000  2026-01-12 12:00:00    1.666667     1191.666667    0.0
min     1.000000  2026-01-10 00:00:00    1.000000      250.000000    0.0
25%     2.250000  2026-01-11 06:00:00    1.250000      550.000000    0.0
50%     3.500000  2026-01-12 12:00:00    2.000000      875.000000    0.0
75%     4.750000  2026-01-13 18:00:00    2.000000     1125.000000    0.0
max     6.000000  2026-01-15 00:00:00    2.000000     3500.000000    0.0
std     1.870829                  NaN    0.516398     1180.430712    0.0

In [91]:
#Média dos valores
df.select_dtypes(include='number').mean()

ID_Pedido            3.500000
Quantidade           1.666667
Valor_Unitario    1191.666667
Total                0.000000
dtype: float64

In [92]:
#Mediana dos valores
df.select_dtypes(include='number').median()

ID_Pedido           3.5
Quantidade          2.0
Valor_Unitario    875.0
Total               0.0
dtype: float64

In [95]:
#Aplicando uma função que substitui a por b
df.apply(lambda x: x.replace('a','b'))

,ID_Pedido,Data,Produto,Categoria,Quantidade,Valor_Unitario,Regiao,Total
0,1,2026-01-10,Notebook,Eletrônicos,1,3500,Sudeste,35000
1,2,2026-01-11,Smartphone,Eletrônicos,2,1200,Nordeste,35000
2,3,2026-01-12,Cadeira Gamer,Móveis,2,850,Sul,35000
3,4,2026-01-13,"Monitor 24""",Eletrônicos,2,900,Sudeste,35000
4,5,2026-01-14,Mesa Escritório,Móveis,2,450,Centro-Oeste,35000
5,6,2026-01-15,Teclado Mecânico,Acessórios,1,250,Norte,35000

In [97]:
#Ordenando o df pela coluna "Valor_Unitario" em ordem crescente
df.sort_values(by="Valor_Unitario")

,ID_Pedido,Data,Produto,Categoria,Quantidade,Valor_Unitario,Regiao,Total
5,6,2026-01-15,Teclado Mecânico,Acessórios,1,250,Norte,0
4,5,2026-01-14,Mesa Escritório,Móveis,2,450,Centro-Oeste,0
2,3,2026-01-12,Cadeira Gamer,Móveis,2,850,Sul,0
3,4,2026-01-13,"Monitor 24""",Eletrônicos,2,900,Sudeste,0
1,2,2026-01-11,Smartphone,Eletrônicos,2,1200,Nordeste,0
0,1,2026-01-10,Notebook,Eletrônicos,1,3500,Sudeste,0

In [98]:
#Ordenando o df pela coluna "Valor_Unitario" em ordem decrescente
df.sort_values(by="Valor_Unitario", ascending=False)

,ID_Pedido,Data,Produto,Categoria,Quantidade,Valor_Unitario,Regiao,Total
0,1,2026-01-10,Notebook,Eletrônicos,1,3500,Sudeste,0
1,2,2026-01-11,Smartphone,Eletrônicos,2,1200,Nordeste,0
3,4,2026-01-13,"Monitor 24""",Eletrônicos,2,900,Sudeste,0
2,3,2026-01-12,Cadeira Gamer,Móveis,2,850,Sul,0
4,5,2026-01-14,Mesa Escritório,Móveis,2,450,Centro-Oeste,0
5,6,2026-01-15,Teclado Mecânico,Acessórios,1,250,Norte,0

### Series usando Pandas

In [104]:
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [100]:
#Somando todos os valores presentes na Series por 2
>>> s.add(2)

a    3
b    4
c    5
d    6
e    7
dtype: int64

In [101]:
#Subtraindo 2 de todos os valores
>>> s.sub(2)

a   -1
b    0
c    1
d    2
e    3
dtype: int64

In [102]:
#Multiplicando todos os valores por 2
>>> s.mul(2)

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [103]:
#Dividindo valores por 2
>>> s.div(2)

a    0.5
b    1.0
c    1.5
d    2.0
e    2.5
dtype: float64

### Outras operações com pandas

In [107]:
#Filtrando o DataFrame para mostrar apenas valores pares
df[df['ID_Pedido'] % 2 == 0]

,ID_Pedido,Data,Produto,Categoria,Quantidade,Valor_Unitario,Regiao,Total
1,2,2026-01-11,Smartphone,Eletrônicos,2,1200,Nordeste,0
3,4,2026-01-13,"Monitor 24""",Eletrônicos,2,900,Sudeste,0
5,6,2026-01-15,Teclado Mecânico,Acessórios,1,250,Norte,0

In [108]:
#Selecionando a primeira linha da coluna país
df.loc[0, 'Produto']

'Notebook'